bool loop 							# when the list of poses exhausted, start over

# Distance and delta yaw at which the target is considered
# as achieved and the next target can be issued
float32 distance_threshold
float32 yaw_threshold

geometry_msgs/PoseStamped[] waypoints 	# list of waypoints (poses) to follow
---
---
uint64 current_index				# index of current target waypoint
float32 distance 					# distance to current target
float32 yaw 						# delta yaw to current target
